# Generated by Django 5.0.4 on 2024-05-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_stockmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='units',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.customer'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tendered_amount',
            field=models.FloatField(default=0),
        ),
    ]
