# Generated by Django 5.0.4 on 2024-06-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_stockmovement_quantity_in_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='tendered_price',
            field=models.FloatField(default=0),
        ),
    ]
