# Generated by Django 5.0.4 on 2024-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_salesitems_change_salesitems_tendered_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tendered_total',
            field=models.FloatField(default=0),
        ),
    ]
