# Generated by Django 5.0.4 on 2024-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_sales_tendered_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='advance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='total_tendered_price',
            field=models.FloatField(default=0),
        ),
    ]
