# Generated by Django 5.0.4 on 2024-06-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_company_paymentmethod_storelocations_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
