# Generated by Django 5.0.4 on 2024-06-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_paymentmethod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.units'),
        ),
    ]
