# Generated by Django 5.0.4 on 2024-06-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_alter_products_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.paymentmethod'),
        ),
    ]
