# Generated by Django 5.0.4 on 2024-06-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0018_stockmovement_quantity_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.products'),
        ),
    ]
