# Generated by Django 5.0.4 on 2024-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0019_alter_stockmovement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
    ]
