# Generated by Django 5.0.4 on 2024-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0020_alter_stockmovement_quantity_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
