# Generated by Django 5.0.4 on 2024-06-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
