# Generated by Django 5.0.4 on 2024-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0024_remove_company_image_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
