# Generated by Django 5.0.4 on 2024-06-25 10:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0027_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='advance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='car_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.paymentmethod'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='tendered_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PurchasesDuePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_loan', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('total_paid_amount', models.FloatField(default=0)),
                ('disbursed_amount', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.purchases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
