# Generated by Django 5.0.4 on 2024-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0028_purchases_advance_amount_purchases_car_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='loan_status',
            field=models.IntegerField(default=0),
        ),
    ]
