# Generated by Django 5.0.4 on 2024-06-27 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0029_purchases_loan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendered_price', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products')),
            ],
        ),
    ]
