# Generated by Django 5.0.4 on 2024-06-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0031_rename_price_customproforma_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproforma',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.customer'),
        ),
    ]
