# Generated by Django 5.0.4 on 2024-07-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0034_alter_purchases_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpurchaseshistory',
            name='outstanding_amount',
        ),
    ]
