# Generated by Django 5.0.4 on 2024-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0035_remove_supplierpurchaseshistory_outstanding_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersaleshistory',
            name='total_paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplierpurchaseshistory',
            name='total_paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
