# Generated by Django 5.0.4 on 2024-07-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0036_customersaleshistory_total_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersaleshistory',
            name='outstanding_amount',
        ),
        migrations.AddField(
            model_name='customersaleshistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.customer'),
        ),
        migrations.AddField(
            model_name='supplierpurchaseshistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posApp.supplier'),
        ),
        migrations.AlterField(
            model_name='customersaleshistory',
            name='sale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.sales'),
        ),
        migrations.AlterField(
            model_name='supplierpurchaseshistory',
            name='purchase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.purchases'),
        ),
    ]
