# Generated by Django 5.0.4 on 2024-07-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0037_remove_customersaleshistory_outstanding_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_loan',
            field=models.BooleanField(default=False),
        ),
    ]
