# Generated by Django 5.0.4 on 2024-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0038_customer_has_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='has_loan',
            field=models.BooleanField(default=False),
        ),
    ]
