# Generated by Django 5.0.4 on 2024-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0039_supplier_has_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='minimum_quantity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
