# Generated by Django 5.0.4 on 2024-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0040_products_minimum_quantity_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
