# Generated by Django 5.0.4 on 2024-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0041_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_direct_pricing_method',
            field=models.BooleanField(default=False),
        ),
    ]
