# Generated by Django 5.0.4 on 2024-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0042_company_is_direct_pricing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='configured',
            field=models.BooleanField(default=False),
        ),
    ]
