# Generated by Django 5.0.4 on 2024-09-13 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0044_customersaleshistory_tendered_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('initial_stock', models.IntegerField(default=0)),
                ('purchased_quantity', models.IntegerField(default=0)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products')),
                ('purchases', models.ManyToManyField(blank=True, null=True, to='posApp.purchases')),
                ('sales', models.ManyToManyField(blank=True, null=True, to='posApp.sales')),
            ],
        ),
    ]
