# Generated by Django 5.0.4 on 2024-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0045_stockmovementhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementhistory',
            name='purchases',
            field=models.ManyToManyField(blank=True, to='posApp.purchases'),
        ),
        migrations.AlterField(
            model_name='stockmovementhistory',
            name='sales',
            field=models.ManyToManyField(blank=True, to='posApp.sales'),
        ),
    ]
