# Generated by Django 5.1.1 on 2024-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0046_alter_stockmovementhistory_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='phone_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
