# Generated by Django 5.1.1 on 2024-10-16 11:23

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):
    dependencies = [
        ('posApp', '0047_sales_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),  # Adjusted max_digits
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),  # Consistent default
        ),
    ]
