# Generated by Django 5.1.1 on 2024-10-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0048_products_markup_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
