# Generated by Django 5.1.1 on 2024-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0049_alter_products_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='max_pieces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='pieces',
            field=models.IntegerField(default=0),
        ),
    ]
