# Generated by Django 5.1.1 on 2024-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0050_products_max_pieces_products_pieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pieces',
            new_name='left_pieces',
        ),
        migrations.AddField(
            model_name='products',
            name='total_pieces',
            field=models.IntegerField(default=0),
        ),
    ]
