# Generated by Django 5.1.1 on 2024-10-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0051_rename_pieces_products_left_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementhistory',
            name='balance_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovementhistory',
            name='initial_stock_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
