# Generated by Django 5.1.1 on 2024-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0052_stockmovementhistory_balance_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='pcs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
