# Generated by Django 5.1.1 on 2024-10-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0053_salesitems_pcs_alter_salesitems_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
